//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//___COPYRIGHT___
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
___COREDATAMANAGEDOBJECTSUPERCLASSIMPORT___
___COREDATAMANAGEDOBJECTCLASSREFERENCES___
@interface ___FILEBASENAMEASIDENTIFIER___ : ___COREDATAMANAGEDOBJECTSUPERCLASS___

___COREDATAPROPERTYDECLARATIONS___
@end
